filter:
  excluded_paths: [tests/*]

build:
  nodes:
    tests-with-coverage:
      environment:
        php:
          version: 8.0
          ini:
            "xdebug.mode": coverage
      tests:
        override:
          - php-scrutinizer-run

checks:
  php:
    fix_doc_comments: true
